---
- name: Preconfig
  hosts: demo
  tasks:
    - name: Install Docker
      block:
        - name: Add Universe
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present

        - name: Install additional packages
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update-cache: true # говорим чтобы обновлялись пакеты
            cache_valid_time: 86400

        - name: Добавление ключа Docker (Add Docker GPG apt Key)
          apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

        - name: Add Docker Repository
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
            state: present
            update-cache: yes
            filename: docker

        - name: Update apt and install docker-ce
          apt: update_cache=yes name=docker-ce state=latest

        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html
        - name: Checking that Docker is installed and rebooted Проверка что Docker установлен и перезагружен
          service:
            name: docker
            state: restarted
            enabled: yes

# https://docs.ansible.com/ansible/latest/collections/index.html